version: 2.1

commands:
  install-deps:
    steps:
      - run:
          name: Create & populate venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

jobs:
  prepare:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - install-deps
      - run:
          name: Run 1_build.py
          command: |
            . venv/bin/activate
            python ml/1_build.py
      # persist both your venv *and* the training_data folder
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - training_data

  train:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: .
      # no install-deps here—venv is already in workspace
      - run:
          name: Run 2_train.py
          command: |
            . venv/bin/activate
            python ml/2_train.py
      - persist_to_workspace:
          root: .
          paths:
            - training_data
            - venv

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run 3_test.py
          command: |
            . venv/bin/activate
            pytest ml/3_test.py

  package:
    docker:
      - image: cimg/python:3.11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run 4_package.py
          command: |
            . venv/bin/activate
            python ml/4_package.py

workflows:
  ml_pipeline:
    jobs:
      - prepare
      - train:
          requires:
            - prepare
      - test:
          requires:
            - train
      - package:
          requires:
            - test
